// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJcb_0ww4HjdCwR0w8ZlNbOWUYpbukVE',
    appId: '1:161838628370:android:30853a0f3a80badf5d62cb',
    messagingSenderId: '161838628370',
    projectId: 'whatsapp-project-13a81',
    storageBucket: 'whatsapp-project-13a81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrJcb_0ww4HjdCwR0w8ZlNbOWUYpbukVE',
    appId: '1:161838628370:android:30853a0f3a80badf5d62cb',
    messagingSenderId: '161838628370',
    projectId: 'whatsapp-project-13a81',
    storageBucket: 'whatsapp-project-13a81.firebasestorage.app',
    iosBundleId: 'com.ovosolution.ovowppapp',
  );
}
