// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJcb_0ww4HjdCwR0w8ZlNbOWUYpbukVE',
    appId: '1:161838628370:android:c31f84da09aabb125d62cb',
    messagingSenderId: '161838628370',
    projectId: 'whatsapp-project-13a81',
    storageBucket: 'whatsapp-project-13a81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrJcb_0ww4HjdCwR0w8ZlNbOWUYpbukVE',
    appId: '1:161838628370:android:c31f84da09aabb125d62cb',
    messagingSenderId: '161838628370',
    projectId: 'whatsapp-project-13a81',
    storageBucket: 'whatsapp-project-13a81.firebasestorage.app',
    iosBundleId: 'com.ovosolution.ovowpp',
  );
}
